### ISSUE TITLE
jquery dependency fails

### ISSUE THREAD

**Issue by atilkan** [ankurk91/vue-trumbowyg#24]
Jquery dep is not specified in package.json but plugin looks for it and can't find.

**Comment by ankurk91** [comment]
Already specified in readme.

https://github.com/ankurk91/vue-trumbowyg/blob/master/README.md#requirements


And here
https://github.com/ankurk91/vue-trumbowyg/blob/1058f9d3d34064e8170147fb0da7bb7cfbc92975/package.json#L60

And here

https://alex-d.github.io/Trumbowyg/documentation/


I wish if I could specify "Google Chrome" in package.json so because the package requires a browser too.

**Comment by atilkan** [comment]
It is your dependency, you should define it in your package

**Comment by ankurk91** [comment]
I have not specified `vue` as well.
But I can think about specifying `jquery`.

**Comment by atilkan** [comment]
Did you just write about Chrome as a dependency. 
I wonder how my email updated as well.

**Comment by ankurk91** [comment]
It is morning time here in India. ;)
Don't worry, will get a new version today with jQuery as a dependency.

**Comment by atilkan** [comment]
Out of curiosity. The question is; Does gmail updates github comments?

**Comment by ankurk91** [comment]
You can reply to the email thread and it will be posted here as a comment.

**Comment by atilkan** [comment]
Nice to know. Thanks.

**Comment by ankurk91** [comment]
published v3.4.2
